### ISSUE TITLE
Multi plot lines, 

### ISSUE THREAD

**Issue by RobTillaart** [MAINAKMONDAL98/MSMPLOTTER#1]
Very inspiring idea. Just a few requests that will pop up soon 

1) can you add a second graph e.g. by using a different character?
2) select the character for the background, e..g. space or '.' 
3) One could save a substantial amount of more memory by printing graphs 90 degrees rotated .
  could be an option.

Thanks for sharing!

**Comment by MAINAKMONDAL98** [comment]
Thanks for the suggestion.I can update those mentioned features in the next version of release.

**Comment by RobTillaart** [comment]
That sounds like a plan. 
The vertical / rotated representation would allow continuous monitoring of the ADC's so that would be really add functionality.

**Comment by MAINAKMONDAL98** [comment]
At first phase I did this vertical representation where x axis was shifted to negative y axis and y axis was shifted to x axis and data streaming was dynamic but I felt that may not be acceptable to Arduino community and also to the users.But when your are supporting this approach then I can attach it as another function.
Thanks for the suggestion.
